/*
 Navicat Premium Data Transfer

 Source Server         : 192.144.133.50
 Source Server Type    : MySQL
 Source Server Version : 80200 (8.2.0)
 Source Host           : 192.144.133.50:3306
 Source Schema         : dormitory

 Target Server Type    : MySQL
 Target Server Version : 80200 (8.2.0)
 File Encoding         : 65001

 Date: 18/08/2024 15:55:28
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `account` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL,
  `username` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL,
  `password` varchar(32) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL,
  `time` datetime NULL DEFAULT NULL,
  `details` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 2 CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES (1, '18329723317', 'admin', '0192023a7bbd73250516f069df18b500', '2024-08-07 08:04:06', '{\"gender\":\"男\",\"hometown\":\"北方\",\"constellation\":\"天蝎座\",\"roommateOrigin\":\"北方\",\"schedule\":\"通常11点之后睡\",\"smoking\":\"否\",\"hygiene\":\"A.很高要求，自认为有“洁癖”\",\"sleepQuality\":5,\"conflictReason\":\"B.作息不一致\",\"harmonyKey\":\"A.生活中能够互相包容理解\",\"mbti\":\"ESFJ\",\"personality\":[\"A.外向热情，广交朋友\"],\"socialStatus\":\"A.社牛型\",\"conflictResolution\":\"是\",\"hobbies\":\"偏静型（读书，绘画等）\",\"gaming\":\"否\",\"postGraduationPlan\":\"A.利用大学时间找到自己的优势，为日后就业做准备\",\"entryGoals\":[\"A.参与学生工作，竞选班委，学生会，锻炼自己的组织领导能力\",\"D.考取相关证书（四六级，计算机，普通话）\"],\"universityGoal\":\"A.学霸型\",\"progressArea\":\"B.独立生活能力\",\"classCommittee\":{\"status\":\"否\",\"position\":\"\"},\"roomRestStatus\":\"早睡早起\",\"smokingRoommate\":\"介意\",\"roomHygiene\":\"A.非常在意寝室的卫生情况，有洁癖\",\"mixedYearRoommates\":3,\"noiseTolerance\":3,\"roommateRegion\":\"B.同一地区\",\"extravertIntrovert\":\"全部I人\",\"importantFactor\":\"兴趣爱好\"}');

SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `users` VALUES 
(2, '15678901234', 'user1', '1234567890abcdef', '2024-08-08 09:05:07', '{"gender":"女","hometown":"南方","constellation":"射手座","roommateOrigin":"南方","schedule":"通常 10 点之后睡","smoking":"否","hygiene":"B.较高要求，保持基本整洁","sleepQuality":4,"conflictReason":"C.性格不合","harmonyKey":"B.尊重彼此的习惯","mbti":"ENFP","personality":["B.活泼开朗，喜欢社交"],"socialStatus":"B.社交活跃型","conflictResolution":"是","hobbies":"偏动型（运动，旅行等）","gaming":"否","postGraduationPlan":"B.考研深造，提升学历","entryGoals":["B.参加社团活动，拓展兴趣爱好","C.参加学术竞赛，提升专业能力"],"universityGoal":"B.平衡发展型","progressArea":"C.沟通表达能力","classCommittee":{"status":"否","position":""},"roomRestStatus":"晚睡晚起","smokingRoommate":"介意","roomHygiene":"B.比较在意寝室的卫生","mixedYearRoommates":2,"noiseTolerance":2,"roommateRegion":"A.不同地区","extravertIntrovert":"部分 E 人","importantFactor":"性格"}'),
(3, '13456789012', 'user2', 'fedcba0987654321', '2024-08-09 10:10:10', '{"gender":"男","hometown":"北方","constellation":"摩羯座","roommateOrigin":"北方","schedule":"通常 12 点之后睡","smoking":"否","hygiene":"A.很高要求，自认为有“洁癖”","sleepQuality":5,"conflictReason":"B.作息不一致","harmonyKey":"A.生活中能够互相包容理解","mbti":"ISTJ","personality":["C.沉稳内敛，做事认真"],"socialStatus":"C.内向专注型","conflictResolution":"是","hobbies":"偏静型（音乐，书法等）","gaming":"否","postGraduationPlan":"C.出国留学，拓宽视野","entryGoals":["D.加入志愿者组织，服务社会","E.参与科研项目，积累经验"],"universityGoal":"C.学术钻研型","progressArea":"D.时间管理能力","classCommittee":{"status":"否","position":""},"roomRestStatus":"早睡早起","smokingRoommate":"不介意","roomHygiene":"A.非常在意寝室的卫生情况，有洁癖","mixedYearRoommates":1,"noiseTolerance":4,"roommateRegion":"B.同一地区","extravertIntrovert":"全部 I 人","importantFactor":"生活习惯"}'),
(4, '17890123456', 'user3', '0987654321abcdef', '2024-08-10 11:11:11', '{"gender":"女","hometown":"东方","constellation":"双鱼座","roommateOrigin":"东方","schedule":"通常 11 点睡","smoking":"否","hygiene":"B.较高要求，保持基本整洁","sleepQuality":3,"conflictReason":"D.生活观念不同","harmonyKey":"C.制定明确的寝室规则","mbti":"INFJ","personality":["D.富有洞察力，理想主义"],"socialStatus":"A.社牛型","conflictResolution":"是","hobbies":"偏静型（写作，摄影等）","gaming":"是","postGraduationPlan":"D.自主创业，实现梦想","entryGoals":["A.参与学生工作，竞选班委，学生会，锻炼自己的组织领导能力","B.参加社团活动，拓展兴趣爱好"],"universityGoal":"A.学霸型","progressArea":"E.团队协作能力","classCommittee":{"status":"是","position":"班长"},"roomRestStatus":"晚睡早起","smokingRoommate":"介意","roomHygiene":"B.比较在意寝室的卫生","mixedYearRoommates":3,"noiseTolerance":1,"roommateRegion":"A.不同地区","extravertIntrovert":"部分 E 人","importantFactor":"价值观"}'),
(5, '10123456789', 'user4', '1111111111111111', '2024-08-11 12:12:12', '{"gender":"男","hometown":"西方","constellation":"狮子座","roommateOrigin":"西方","schedule":"通常 9 点睡","smoking":"是","hygiene":"C.一般要求，不太在意","sleepQuality":2,"conflictReason":"A.个人空间被侵犯","harmonyKey":"D.经常进行寝室交流","mbti":"ESTP","personality":["E.勇敢果断，敢于冒险"],"socialStatus":"B.社交活跃型","conflictResolution":"是","hobbies":"偏动型（篮球，游泳等）","gaming":"是","postGraduationPlan":"E.先就业再择业","entryGoals":["C.参加实习，积累工作经验","D.加入兴趣小组，提升专业技能"],"universityGoal":"B.平衡发展型","progressArea":"F.情绪管理能力","classCommittee":{"status":"否","position":""},"roomRestStatus":"早睡晚起","smokingRoommate":"不介意","roomHygiene":"C.不太在意寝室的卫生","mixedYearRoommates":2,"noiseTolerance":5,"roommateRegion":"B.同一地区","extravertIntrovert":"全部 E 人","importantFactor":"兴趣"}'),
(6, '12345678901', 'user5', '2222222222222222', '2024-08-12 13:13:13', '{"gender":"女","hometown":"北方","constellation":"天秤座","roommateOrigin":"北方","schedule":"通常 10 点睡","smoking":"否","hygiene":"A.很高要求，自认为有“洁癖”","sleepQuality":5,"conflictReason":"B.作息不一致","harmonyKey":"A.生活中能够互相包容理解","mbti":"ESFJ","personality":["A.外向热情，广交朋友"],"socialStatus":"A.社牛型","conflictResolution":"是","hobbies":"偏静型（手工，烘焙等）","gaming":"否","postGraduationPlan":"A.利用大学时间找到自己的优势，为日后就业做准备","entryGoals":["A.参与学生工作，竞选班委，学生会，锻炼自己的组织领导能力","D.考取相关证书（四六级，计算机，普通话）"],"universityGoal":"A.学霸型","progressArea":"B.独立生活能力","classCommittee":{"status":"是","position":"学习委员"},"roomRestStatus":"早睡早起","smokingRoommate":"介意","roomHygiene":"A.非常在意寝室的卫生情况，有洁癖","mixedYearRoommates":3,"noiseTolerance":3,"roommateRegion":"B.同一地区","extravertIntrovert":"部分 I 人","importantFactor":"生活习惯"}'),
(7, '14567890123', 'user6', '3333333333333333', '2024-08-13 14:14:14', '{"gender":"男","hometown":"南方","constellation":"巨蟹座","roommateOrigin":"南方","schedule":"通常 11 点睡","smoking":"否","hygiene":"B.较高要求，保持基本整洁","sleepQuality":4,"conflictReason":"C.性格不合","harmonyKey":"B.尊重彼此的习惯","mbti":"INFP","personality":["F.富有想象力，内心丰富"],"socialStatus":"C.内向专注型","conflictResolution":"是","hobbies":"偏静型（观影，追剧等）","gaming":"否","postGraduationPlan":"B.考研深造，提升学历","entryGoals":["B.参加社团活动，拓展兴趣爱好","C.参加学术竞赛，提升专业能力"],"universityGoal":"B.平衡发展型","progressArea":"C.沟通表达能力","classCommittee":{"status":"否","position":""},"roomRestStatus":"晚睡晚起","smokingRoommate":"介意","roomHygiene":"B.比较在意寝室的卫生","mixedYearRoommates":2,"noiseTolerance":2,"roommateRegion":"A.不同地区","extravertIntrovert":"全部 I 人","importantFactor":"性格"}'),
(8, '16789012345', 'user7', '4444444444444444', '2024-08-14 15:15:15', '{"gender":"女","hometown":"东方","constellation":"双子座","roommateOrigin":"东方","schedule":"通常 12 点睡","smoking":"否","hygiene":"A.很高要求，自认为有“洁癖”","sleepQuality":5,"conflictReason":"B.作息不一致","harmonyKey":"A.生活中能够互相包容理解","mbti":"ENTP","personality":["G.思维敏捷，善于创新"],"socialStatus":"A.社牛型","conflictResolution":"是","hobbies":"偏动型（跳舞，瑜伽等）","gaming":"是","postGraduationPlan":"D.自主创业，实现梦想","entryGoals":["A.参与学生工作，竞选班委，学生会，锻炼自己的组织领导能力","B.参加社团活动，拓展兴趣爱好"],"universityGoal":"A.学霸型","progressArea":"E.团队协作能力","classCommittee":{"status":"是","position":"团支书"},"roomRestStatus":"晚睡早起","smokingRoommate":"介意","roomHygiene":"A.非常在意寝室的卫生情况，有洁癖","mixedYearRoommates":3,"noiseTolerance":1,"roommateRegion":"B.同一地区","extravertIntrovert":"部分 E 人","importantFactor":"价值观"}'),
(9, '18901234567', 'user8', '5555555555555555', '2024-08-15 16:16:16', '{"gender":"男","hometown":"西方","constellation":"金牛座","roommateOrigin":"西方","schedule":"通常 10 点睡","smoking":"否","hygiene":"B.较高要求，保持基本整洁","sleepQuality":3,"conflictReason":"D.生活观念不同","harmonyKey":"C.制定明确的寝室规则","mbti":"ISTP","personality":["H.冷静理性，注重实际"],"socialStatus":"B.社交活跃型","conflictResolution":"是","hobbies":"偏静型（下棋，钓鱼等）","gaming":"否","postGraduationPlan":"E.先就业再择业","entryGoals":["C.参加实习，积累工作经验","D.加入兴趣小组，提升专业技能"],"universityGoal":"B.平衡发展型","progressArea":"F.情绪管理能力","classCommittee":{"status":"否","position":""},"roomRestStatus":"早睡晚起","smokingRoommate":"不介意","roomHygiene":"C.不太在意寝室的卫生","mixedYearRoommates":2,"noiseTolerance":5,"roommateRegion":"A.不同地区","extravertIntrovert":"全部 E 人","importantFactor":"兴趣"}'),
(10, '11234567890', 'user9', '6666666666666666', '2024-08-16 17:17:17', '{"gender":"女","hometown":"北方","constellation":"水瓶座","roommateOrigin":"北方","schedule":"通常 9 点睡","smoking":"否","hygiene":"A.很高要求，自认为有“洁癖”","sleepQuality":5,"conflictReason":"B.作息不一致","harmonyKey":"A.生活中能够互相包容理解","mbti":"ENFJ","personality":["I.热情友善，富有领导力"],"socialStatus":"A.社牛型","conflictResolution":"是","hobbies":"偏动型（登山，骑行等）","gaming":"是","postGraduationPlan":"A.利用大学时间找到自己的优势，为日后就业做准备","entryGoals":["A.参与学生工作，竞选班委，学生会，锻炼自己的组织领导能力","D.考取相关证书（四六级，计算机，普通话）"],"universityGoal":"A.学霸型","progressArea":"B.独立生活能力","classCommittee":{"status":"是","position":"文艺委员"},"roomRestStatus":"早睡早起","smokingRoommate":"介意","roomHygiene":"A.非常在意寝室的卫生情况，有洁癖","mixedYearRoommates":3,"noiseTolerance":3,"roommateRegion":"B.同一地区","extravertIntrovert":"部分 I 人","importantFactor":"生活习惯"}'),
(11, '13456789012', 'user10', '7777777777777777', '2024-08-17 18:18:18', '{"gender":"男","hometown":"南方","constellation":"白羊座","roommateOrigin":"南方","schedule":"通常 11 点睡","smoking":"否","hygiene":"B.较高要求，保持基本整洁","sleepQuality":4,"conflictReason":"C.性格不合","harmonyKey":"B.尊重彼此的习惯","mbti":"INTJ","personality":["J.独立思考，有战略眼光"],"socialStatus":"C.内向专注型","conflictResolution":"是","hobbies":"偏静型（阅读，冥想等）","gaming":"否","postGraduationPlan":"B.考研深造，提升学历","entryGoals":["B.参加社团活动，拓展兴趣爱好","C.参加学术竞赛，提升专业能力"],"universityGoal":"B.平衡发展型","progressArea":"C.沟通表达能力","classCommittee":{"status":"否","position":""},"roomRestStatus":"晚睡晚起","smokingRoommate":"介意","roomHygiene":"B.比较在意寝室的卫生","mixedYearRoommates":2,"noiseTolerance":2,"roommateRegion":"A.不同地区","extravertIntrovert":"全部 I 人","importantFactor":"性格"}'),
(12, '15678901234', 'user11', '8888888888888888', '2024-08-18 19:19:19', '{"gender":"女","hometown":"东方","constellation":"处女座","roommateOrigin":"东方","schedule":"通常 10 点睡","smoking":"否","hygiene":"A.很高要求，自认为有“洁癖”","sleepQuality":5,"conflictReason":"B.作息不一致","harmonyKey":"A.生活中能够互相包容理解","mbti":"ESFP","personality":["K.乐观开朗，享受当下"],"socialStatus":"A.社牛型","conflictResolution":"是","hobbies":"偏动型（轮滑，滑板等）","gaming":"是","postGraduationPlan":"D.自主创业，实现梦想","entryGoals":["A.参与学生工作，竞选班委，学生会，锻炼自己的组织领导能力","B.参加社团活动，拓展兴趣爱好"],"universityGoal":"A.学霸型","progressArea":"E.团队协作能力","classCommittee":{"status":"是","position":"组织委员"},"roomRestStatus":"晚睡早起","smokingRoommate":"介意","roomHygiene":"A.非常在意寝室的卫生情况，有洁癖","mixedYearRoommates":3,"noiseTolerance":1,"roommateRegion":"B.同一地区","extravertIntrovert":"部分 E 人","importantFactor":"价值观"}');